### PR TITLE
Cleanup web; Fix navbar; Load packages asynchronously

### LINKED ISSUE #7: Header navbar doesn't work
In the new design the "Choose a page..." navbar does not do anything. We should choose landing targets (maybe XRPackage Browse, Metachromium, Docs), and either add the links to the header or use `selector.js` to enable the selector.

Screen Shot 2020-06-10 at 10 36 23 AM

### PR DESCRIPTION
**Pull request by shu8**
This PR:
- removes old/unused files,
- fixes the navbar so it is clickable,
- changes package load behaviour so that they appear as soon as they are loaded, rather than loading each one linearly by `await`ing them
  This seems to be better because normally there is a black screen for a few seconds, before all the packages start loading, so at first glance the page looks boring. Whereas now, packages will start appearing as soon as they are ready.

Closes #7.

### CODE REVIEW

**Comment by avaer** [comment]
Thanks, this is a good idea.

File: app.js [hunk 1]
```diff
@@ -26,84 +24,102 @@ const localMatrix = new THREE.Matrix4();
 
   {
     console.log('load logo');
-    const res = await fetch('./augs/webaverse-logo/a.wbn');
-    const ab = await res.arrayBuffer();
-    const uint8Array = new Uint8Array(ab);
-    const p = new XRPackage(uint8Array);
-    p.setMatrix(localMatrix.compose(localVector.set(0, 0, 0), localQuaternion.set(0, 0, 0, 1), localVector2.set(1, 1, 1)));
-    await pe.add(p);
+    fetch('./augs/webaverse-logo/a.wbn').then(res => {
```
Comment (avaer) [inline app.js]: I think we can still use `await` with a function wrapping:

```
(async () => {
})();
```

It would still behave the same without needing `.then` chains.

**Review by avaer — COMMENTED** [review]
Recommended a wait we can still keep `async`-`await`.

File: app.js (hunk 1 above)
Comment (shu8) [reply app.js]: Sorry, I'm a little unsure what you mean here! are you saying to `await` the `fetch` call?

**Comment by avaer** [comment]
This will also need a rebase.

**Comment by shu8** [comment]
Thanks @avaer, I just rebased. I'm a bit confused what you meant by wrapping `async` function, could you post an example of what I could be doing?

File: app.js (hunk 1 above)
Comment (avaer) [reply app.js]: Yes, in that function.

**Comment by avaer** [comment]
This is the style virtually all of our packages use when doing async loading.

**Comment by avaer** [comment]
https://github.com/avaer/lightsaber/blob/698ff0efa9bd0ed1e4b13bf7e632c1b59f6653d5/lightsaber.html#L68

File: app.js (hunk 1 above)
Comment (shu8) [reply app.js]: Would this mean that the packages still need to load one after the other?

```
  {
    console.log('load logo');
    await fetch('./augs/webaverse-logo/a.wbn').then(res => {
      res.arrayBuffer().then(ab => {
        const uint8Array = new Uint8Array(ab);
        const p = new XRPackage(uint8Array);
        p.setMatrix(localMatrix.compose(localVector.set(0, 0, 0), localQuaternion.set(0, 0, 0, 1), localVector2.set(1, 1, 1)));
        pe.add(p);
      });
    });
  }
```

Comment (avaer) [reply app.js]: No because there would be 5+ such functions.

Comment (avaer) [reply app.js]: Also, the above code somewhat defeats the point of simplification since it is still using `.then` chaining.

Comment (shu8) [reply app.js]: Oh, do you mean wrapping each of those blocks into an `async` function like this?

```
(async () => {
    console.log('load logo');
    const res = await fetch('./augs/webaverse-logo/a.wbn');
    const ab = await res.arrayBuffer();
    const uint8Array = new Uint8Array(ab);
    const p = new XRPackage(uint8Array);
    p.setMatrix(localMatrix.compose(localVector.set(0, 0, 0), localQuaternion.set(0, 0, 0, 1), localVector2.set(1, 1, 1)));
    await pe.add(p);
  })()
```

Comment (avaer) [reply app.js]: Correct, and they will all work in parallel.

Comment (shu8) [reply app.js]: Ah okay that makes sense, thanks! will push

Comment (shu8) [reply app.js]: Just pushed this change! 🙂

**Comment by shu8** [comment]
@avaer Am I okay to merge this? I'm not sure if you wanted to have another review after adding the `(async() => { ... })()` wrappers around the package loaders!

**Review by avaer — APPROVED** [review]
Looks good now 👍 .
